permalink: pretty

gems:
  - jekyll-redirect-from

collections:
  events:
    output: true
    permalink: /events/:path/
  models:
    output: true
    permalink: /models/:path/
  projects:
    output: true
    permalink: /projects/:path/